### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by attilaaf** [bitcoin-sv/minerid-reference#7]
**Describe the bug**
Unable to generaate minerid using command line

**To Reproduce** 

Create default.json -> config.json in the /config directory.

Run command:

WARNING: No configurations found in configuration directory:/home/ubuntu/minerid-reference/config

**Expected behavior**

Expected miner id to be generated

**Screenshots & Logs**

npm run cli -- generateminerid --name FOOBAR

> builder@0.2.0 cli /home/ubuntu/minerid-reference
> node cli.js "generateminerid" "--name" "FOOBAR"

WARNING: No configurations found in configuration directory:/home/ubuntu/minerid-reference/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/home/ubuntu/minerid-reference/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "network" is not defined
    at Config.get (/home/ubuntu/minerid-reference/node_modules/config/lib/config.js:182:11)
    at Object.<anonymous> (/home/ubuntu/minerid-reference/cli.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! builder@0.2.0 cli: `node cli.js "generateminerid" "--name" "FOOBAR"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the builder@0.2.0 cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-21T05_23_07_271Z-debug.log

**System Information (please complete the following information):**
 
latest version. ubuntu  20.04

**Additional context**

**Comment by attilaaf** [comment]
Non-issue, I was missing a key in the file.
